### ISSUE TITLE
Driver continually loops historic period preventing report generation

### ISSUE THREAD

**Issue by m90att** [AussieSusan/HP1000#10]
HI @AussieSusan 

Great driver.  I've used it for years with no issue.  Suddenly on 5th Jan I saw it trying to obtain records from the weather station from September 2020, over and over and over again, incessantly, without stopping and while it was doing that it prevented the report generation.  This means that I have no reports.  The only way to generate reports is manually run wee_reports.

I have done a couple of completely fresh installs using the latest version but I'm seeing exactly the same thing.  Salient syslog entries are below, do you know what the cause is and whether it can be resolved.  At the moment I cannot use weewx as a result.

Many thanks,

Matt

```
Jan 16 19:00:48 weatherpi weewx[849] INFO root: HP100: Timed out too many times
Jan 16 19:01:13 weatherpi weewx[849] INFO root: HP100: Timed out too many times
Jan 16 19:01:19 weatherpi weewx[849] INFO root: HP100: Connected to address ('192.168.86.35', 60038)
Jan 16 19:01:20 weatherpi weewx[849] INFO root: HP100: Established contact at 16/01/21 19:01:20
Jan 16 19:01:20 weatherpi weewx[849] INFO root: HP100: Retrieving startup records
Jan 16 19:01:31 weatherpi weewx[849] INFO weewx.manager: Added record 2021-01-16 18:55:15 GMT (1610823315) to database 'weewx.sdb'
Jan 16 19:01:31 weatherpi weewx[849] INFO weewx.manager: Added record 2021-01-16 18:55:15 GMT (1610823315) to daily summary in 'weewx.sdb'
Jan 16 19:01:31 weatherpi nmbd[533]: [2021/01/16 19:01:31.554850, 0] ../source3/nmbd/nmbd_namequery.c:109(query_name_response)
Jan 16 19:01:31 weatherpi nmbd[533]: query_name_response: Multiple (2) responses received for a query on subnet 192.168.86.40 for name WORKGROUP$
Jan 16 19:01:31 weatherpi nmbd[533]: This response was from IP 192.168.86.26, reporting an IP address of 192.168.86.26.
Jan 16 19:01:32 weatherpi weewx[849] INFO weewx.engine: Main loop exiting. Shutting engine down.
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: Caught OSError: [Errno 5] Input/output error
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** Traceback (most recent call last):
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** File "./bin/weewxd", line 154, in main
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** engine.run()
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** File "/home/weewx/bin/weewx/engine.py", line 178, in run
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** self.dispatchEvent(weewx.Event(weewx.STARTUP))
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** callback(event)
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** File "/home/weewx/bin/weewx/engine.py", line 567, in startup
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** self._catchup(self.engine.console.genStartupRecords)
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** File "/home/weewx/bin/weewx/engine.py", line 682, in _catchup
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** origin='hardware'))
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** File "/home/weewx/bin/weewx/engine.py", line 245, in dispatchEvent
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** callback(event)
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** File "/home/weewx/bin/weewx/engine.py", line 787, in new_archive_record
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** to_sorted_string(event.record))
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** OSError: [Errno 5] Input/output error
Jan 16 19:01:32 weatherpi weewx[849] CRITICAL __main__: **** Waiting 10 seconds then retrying...
Jan 16 19:01:42 weatherpi weewx[849] INFO __main__: retrying...
Jan 16 19:01:42 weatherpi weewx[849] INFO __main__: Using configuration file /home/weewx/weewx.conf
Jan 16 19:01:42 weatherpi weewx[849] INFO __main__: Debug is 1
Jan 16 19:01:42 weatherpi weewx[849] DEBUG __main__: Initializing engine
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.engine: Loading station type HP1000 (user.HP1000)
Jan 16 19:01:42 weatherpi weewx[849] INFO root: HP100: HP1000 Starting
Jan 16 19:01:42 weatherpi weewx[849] INFO root: HP100: Using user-defined broadcast mask - 192.168.86.35
Jan 16 19:01:42 weatherpi weewx[849] INFO root: HP100: Address Mask = 192.168.86.35
Jan 16 19:01:42 weatherpi weewx[849] INFO root: HP100: Retry count = 5.000000
Jan 16 19:01:42 weatherpi weewx[849] INFO root: HP100: Socket timeout = 5.000000
Jan 16 19:01:42 weatherpi weewx[849] INFO root: HP100: Loop delay = 15.000000
Jan 16 19:01:42 weatherpi weewx[849] INFO root: HP100: Retry Wait = 5.000000
Jan 16 19:01:42 weatherpi weewx[849] INFO root: HP100: Max Retry = 3.000000
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.engine.StdTimeSynch
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.engine.StdTimeSynch


Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.engine.StdTimeSynch
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.engine.StdTimeSynch
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.engine.StdConvert
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.engine: StdConvert target unit is 0x1
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.engine.StdConvert
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.engine.StdCalibrate
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.engine.StdCalibrate
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.engine.StdQC
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.engine.StdQC
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.wxservices.StdWXCalculate
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.manager: Daily summary version is 3.0
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.wxservices.StdWXCalculate
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdWXXTypes
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdWXXTypes
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdPressureCooker
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdPressureCooker
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdRainRater
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdRainRater
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdDelta
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdDelta
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.engine.StdArchive
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.engine: Archive will use data binding wx_binding
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.engine: Record generation will be attempted in 'software'
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.engine: Using archive interval of 300 seconds (software record generation)
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Use LOOP data in hi/low calculations: 1
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.engine.StdArchive
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.restx.StdStationRegistry
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.restx: StationRegistry: Registration not requested.
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.restx.StdStationRegistry
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.restx.StdWunderground
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.restx: Wunderground: Posting not enabled.
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.restx.StdWunderground
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.restx.StdPWSweather
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.restx: PWSweather: Posting not enabled.
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.restx.StdPWSweather
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.restx.StdCWOP
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.restx: CWOP: Posting not enabled.
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.restx.StdCWOP
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.restx.StdWOW
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.restx: WOW: Posting not enabled.
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.restx.StdWOW
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.restx.StdAWEKAS
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.restx: AWEKAS: Posting not enabled.
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.restx.StdAWEKAS
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.engine.StdPrint


Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.restx.StdAWEKAS
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.engine.StdPrint
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.engine.StdPrint
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Loading service weewx.engine.StdReport
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Finished loading service weewx.engine.StdReport
Jan 16 19:01:42 weatherpi weewx[849] INFO __main__: Starting up weewx version 4.3.0
Jan 16 19:01:42 weatherpi weewx[849] DEBUG weewx.engine: Station does not support reading the time
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Jan 16 19:01:42 weatherpi weewx[849] INFO weewx.manager: Starting backfill of daily summaries
Jan 16 19:01:43 weatherpi weewx[1246] INFO __main__: retrying...
Jan 16 19:01:43 weatherpi weewx[1246] INFO __main__: Using configuration file /home/weewx/weewx.conf
Jan 16 19:01:43 weatherpi weewx[1246] INFO __main__: Debug is 1
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG __main__: Initializing engine
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.engine: Loading station type HP1000 (user.HP1000)
Jan 16 19:01:43 weatherpi weewx[1246] INFO root: HP100: HP1000 Starting
Jan 16 19:01:43 weatherpi weewx[1246] INFO root: HP100: Using user-defined broadcast mask - 192.168.86.35
Jan 16 19:01:43 weatherpi weewx[1246] INFO root: HP100: Address Mask = 192.168.86.35
Jan 16 19:01:43 weatherpi weewx[1246] INFO root: HP100: Retry count = 5.000000
Jan 16 19:01:43 weatherpi weewx[1246] INFO root: HP100: Socket timeout = 5.000000
Jan 16 19:01:43 weatherpi weewx[1246] INFO root: HP100: Loop delay = 15.000000
Jan 16 19:01:43 weatherpi weewx[1246] INFO root: HP100: Retry Wait = 5.000000
Jan 16 19:01:43 weatherpi weewx[1246] INFO root: HP100: Max Retry = 3.000000
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.engine.StdTimeSynch
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.engine.StdTimeSynch
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.engine.StdConvert
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.engine: StdConvert target unit is 0x1
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.engine.StdConvert
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.engine.StdCalibrate
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.engine.StdCalibrate
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.engine.StdQC
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.engine.StdQC
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.wxservices.StdWXCalculate
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.manager: Daily summary version is 3.0
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.wxservices.StdWXCalculate
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdWXXTypes
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdWXXTypes
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdPressureCooker
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdPressureCooker
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdRainRater
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdRainRater
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.wxxtypes.StdDelta
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.wxxtypes.StdDelta
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.engine.StdArchive
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.engine: Archive will use data binding wx_binding
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.engine: Record generation will be attempted in 'software'
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.engine: Archive will use data binding wx_binding
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.engine: Record generation will be attempted in 'software'
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.engine: Using archive interval of 300 seconds (software record generation)
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Use LOOP data in hi/low calculations: 1
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.engine.StdArchive
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.restx.StdStationRegistry
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.restx: StationRegistry: Registration not requested.
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.restx.StdStationRegistry
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.restx.StdWunderground
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.restx: Wunderground: Posting not enabled.
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.restx.StdWunderground
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.restx.StdPWSweather
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.restx: PWSweather: Posting not enabled.
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.restx.StdPWSweather
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.restx.StdCWOP
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.restx: CWOP: Posting not enabled.
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.restx.StdCWOP
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.restx.StdWOW
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.restx: WOW: Posting not enabled.
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.restx.StdWOW
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.restx.StdAWEKAS
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.restx: AWEKAS: Posting not enabled.
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.restx.StdAWEKAS
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.engine.StdPrint
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.engine.StdPrint
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Loading service weewx.engine.StdReport
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Finished loading service weewx.engine.StdReport
Jan 16 19:01:43 weatherpi weewx[1246] INFO __main__: Starting up weewx version 4.3.0
Jan 16 19:01:43 weatherpi weewx[1246] DEBUG weewx.engine: Station does not support reading the time
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Jan 16 19:01:43 weatherpi weewx[1246] INFO weewx.manager: Starting backfill of daily summaries
Jan 16 19:02:04 weatherpi weewx[1246] INFO root: HP100: Connected to address ('192.168.86.35', 60043)
Jan 16 19:02:05 weatherpi weewx[1246] INFO root: HP100: Established contact at 16/01/21 19:02:05
Jan 16 19:02:05 weatherpi weewx[1246] INFO root: HP100: Retrieving startup records
Jan 16 19:02:07 weatherpi weewx[849] INFO root: HP100: Timed out too many times
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 01:34:13 BST (1599525253) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 01:39:13 BST (1599525553) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 01:44:13 BST (1599525853) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 01:49:13 BST (1599526153) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 01:54:13 BST (1599526453) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 01:59:13 BST (1599526753) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 02:04:13 BST (1599527053) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 02:09:13 BST (1599527353) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 02:14:13 BST (1599527653) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 02:19:13 BST (1599527953) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 02:14:13 BST (1599527653) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 02:19:13 BST (1599527953) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 02:24:13 BST (1599528253) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 02:29:13 BST (1599528553) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 02:34:13 BST (1599528853) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 09:39:10 BST (1599554350) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 09:44:10 BST (1599554650) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 09:49:10 BST (1599554950) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 09:54:10 BST (1599555250) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 09:59:10 BST (1599555550) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:04:10 BST (1599555850) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:09:10 BST (1599556150) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:14:10 BST (1599556450) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:19:10 BST (1599556750) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:24:10 BST (1599557050) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:29:10 BST (1599557350) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:16 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:34:10 BST (1599557650) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:39:10 BST (1599557950) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:44:10 BST (1599558250) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:49:10 BST (1599558550) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:54:10 BST (1599558850) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 10:59:10 BST (1599559150) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:04:10 BST (1599559450) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:09:10 BST (1599559750) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:14:10 BST (1599560050) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:19:10 BST (1599560350) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:24:10 BST (1599560650) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:29:10 BST (1599560950) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:34:10 BST (1599561250) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:39:10 BST (1599561550) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:44:10 BST (1599561850) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:49:10 BST (1599562150) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:54:10 BST (1599562450) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 11:59:10 BST (1599562750) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:04:10 BST (1599563050) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:09:10 BST (1599563350) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:14:10 BST (1599563650) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:19:10 BST (1599563950) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:24:10 BST (1599564250) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:29:10 BST (1599564550) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:34:10 BST (1599564850) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:17 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:39:10 BST (1599565150) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:18 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:44:10 BST (1599565450) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:18 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:49:10 BST (1599565750) to database 'weewx.sdb': UNIQ$
Jan 16 19:02:18 weatherpi weewx[1246] ERROR weewx.manager: Unable to add record 2020-09-08 12:54:10 BST (1599566050) to database 'weewx.sdb': UNIQ$
```

**Comment by m90att** [comment]
i have resolved this by factory resetting my weather station!
