### ISSUE TITLE
Falling at first hurdle

### ISSUE THREAD

**Issue by m90att** [AussieSusan/HP1000#9]
Hi,

I'm trying to install the updated driver but I'm falling at the first hurdle.  I've used the previous version for years and it's fantastic, never misses a beat.

When I wget it to my Raspberry Pi there is no file called HP1000 so wee_extension fails.  I've tried various commands, various downloads and they all fail.

`HP1000.tar.gz  master.zip `

```
pi@weatherpi:/home/weewx/bin $ sudo python3 ./wee_extension --install /tmp/HP1000.tar.gz
Request to install '/tmp/HP1000.tar.gz'
Extracting from tar archive /tmp/HP1000.tar.gz
Traceback (most recent call last):
  File "./wee_extension", line 88, in <module>
    main()
  File "./wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/home/weewx/bin/weecfg/extension.py", line 118, in install_extension
    self.tmpdir, self.logger)
  File "/home/weewx/bin/weecfg/__init__.py", line 1808, in extract_tar
    tar_archive = tarfile.open(filename, mode='r')
  File "/usr/lib/python3.7/tarfile.py", line 1580, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

```
pi@weatherpi:/home/weewx/bin $ sudo python3 ./wee_extension --install /tmp/master.zip
Request to install '/tmp/master.zip'
Extracting from zip archive /tmp/master.zip
Traceback (most recent call last):
  File "/home/weewx/bin/weecfg/__init__.py", line 1866, in get_extension_installer
    __import__('install')
ModuleNotFoundError: No module named 'install'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./wee_extension", line 88, in <module>
    main()
  File "./wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/home/weewx/bin/weecfg/extension.py", line 125, in install_extension
    self.install_from_dir(extension_dir)
  File "/home/weewx/bin/weecfg/extension.py", line 147, in install_from_dir
    extension_dir)
  File "/home/weewx/bin/weecfg/__init__.py", line 1868, in get_extension_installer
    raise ExtensionError("Cannot find 'install' module in %s" % extension_installer_dir)
weecfg.ExtensionError: Cannot find 'install' module in /var/tmp/HP1000-master/

```
I know this is basics but if you don't know, you don't know!

Are you able to see what I'm doing wrong?

Many thanks,

Matt

**Comment by m90att** [comment]
Hurrah for trial and error:

wget -P /var/tmp weewx-hp1000.zip https://github.com/AussieSusan/HP1000/archive/master.zip
cd var/tmp
unzip master.zip
sudo ./wee_extension --install=/var/tmp/HP1000-master/hp1000.tar.gz
sudo ./wee_config --reconfigure
